Repository UMC-Master/backend, pull requests merged in 2025-01, with the labels that each got.

#5 📚docs: Update README.md
  README.md
Labels: :page_facing_up: documentation

#7 ✨feat: 초기 셋팅 완료 및 기본 설정
  .gitignore
  .vscode/settings.json
  dist/index.cjs
  package-lock.json
  package.json
  prisma/schema.prisma
  scripts/build.ts
  src/controllers/user.controller.ts
  src/db.config.js
  src/dtos/user.dto.ts
  src/errors.ts
  src/index.ts
  src/repositories/user.repository.ts
  src/services/user.service.ts
  tsconfig.json
Labels: :gear: Settring

#8 ✨feat: 초기 셋팅 완료 및 기본 설정
  .gitignore
  .vscode/settings.json
  dist/index.cjs
  package-lock.json
  package.json
  prisma/schema.prisma
  scripts/build.ts
  src/controllers/user.controller.ts
  src/db.config.js
  src/dtos/user.dto.ts
  src/errors.ts
  src/index.ts
  src/repositories/user.repository.ts
  src/services/user.service.ts
  tsconfig.json
Labels: :gear: Settring

#10 Feature/apply eslint prettier
  .eslintrc.js
  .prettierrc
  .vscode/settings.json
  eslint.config.js
  package-lock.json
  package.json
  src/errors.ts
  src/index.ts
  types/express.d.ts
Labels: :broom: Chore

#13 ✨ Feat: db 초기 마이그레이션
  prisma/migrations/20250110102100_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
Labels: :sparkles: Feature

#22 fix: prettier 적용 수정
  .vscode/settings.json
  eslint.config.js
  src/controllers/notification.controller.ts
  src/controllers/user.controller.ts
  src/db.config.js
  src/dtos/user.dto.ts
  src/index.ts
  src/repositories/user.repository.ts
Labels: :lady_beetle: BugFix

#27 ✨ Feat: 이메일 로그인 기능 구현
  package-lock.json
  package.json
  prisma/migrations/20250112081922_add_last_login/migration.sql
  prisma/schema.prisma
  src/controllers/user.controller.ts
  src/dtos/user.dto.ts
  src/index.ts
  src/repositories/user.repository.ts
  src/services/user.service.ts
  types/express.d.ts
Labels: :sparkles: Feature

#29 Feature/create api controller
  prisma/migrations/20250112112251_new/migration.sql
  prisma/schema.prisma
  src/controllers/analyze.controller.ts
  src/controllers/policy.controller.ts
  src/controllers/quiz.controller.ts
  src/controllers/tip.controller.ts
  src/controllers/user.manage.controller.ts
  src/dtos/policy.dto.ts
  src/dtos/quiz.dto.ts
  src/dtos/tip.dto.ts
  src/index.ts
  src/services/user.service.ts
Labels: :sparkles: Feature

#32 ✨ Feat: CI/CD 파이프라인 구축
  .github/workflows/deploy-develop.yml
Labels: :sparkles: Feature

#41 feat: 프리즈마 테이블 이름 설정 및 해시태그 타입 구분
  prisma/schema.prisma
Labels: :hammer_and_wrench: Refactor

#43 ✨ Feat: 사용자 관련 API 개선 및 인증 로직 추가
  prisma/migrations/20250117163404_add_status_to_user/migration.sql
  prisma/schema.prisma
  src/controllers/user.controller.ts
  src/middlewares/authenticateJWT.ts
  src/repositories/user.repository.ts
  src/services/user.service.ts
Labels: :sparkles: Feature

#59 Feature: policy crud
  prisma/migrations/20250124134752_aaa/migration.sql
  prisma/schema.prisma
  src/controllers/policy.controller.ts
  src/controllers/user.controller.ts
  src/dtos/policy.dto.ts
  src/errors/errors.ts
  src/errors/hashtag.error.ts
  src/errors/location.error.ts
  src/errors/organization.error.ts
  src/errors/policy.error.ts
  src/middlewares/errorHandler.ts
  src/repositories/hashtag.repository.ts
  src/repositories/location.repository.ts
  src/repositories/magazineBookmark.repository.ts
  src/repositories/magazineHashtag.repository.ts
  src/repositories/magezineLike.repository.ts
  src/repositories/organization.repository.ts
  src/repositories/policy.repository.ts
  src/repositories/user.repository.ts
  src/services/community.service.ts
  src/services/location.service.ts
  src/services/organization.service.ts
  src/services/policy.service.ts
  src/services/tip.service.ts
  src/services/user.service.ts
Labels: :sparkles: Feature

#63 Fix: swagger servers list
  src/swagger.ts
Labels: :sparkles: Feature

#65 Fix: swagger servers list
  src/swagger.ts
Labels: :sparkles: Feature

#67 feat: 매거진 응답에 공통 응답 설정
  src/controllers/policy.controller.ts
Labels: :sparkles: Feature

#71 Feature: location crud
  src/controllers/location.controller.ts
  src/controllers/policy.controller.ts
  src/dtos/location.dto.ts
  src/errors/location.error.ts
  src/index.ts
  src/repositories/location.repository.ts
  src/services/location.service.ts
  types/express.d.ts
Labels: :sparkles: Feature

#75 feat: 퀴즈 더미 데이터 반환
  src/controllers/quiz.controller.ts
Labels: :sparkles: Feature
